version: '3.9'
services:
  events-api:
    image: events-api
    container_name: events_api_application
    command: dotnet ef database update
    ports:
      - "5000:80"
    networks:
      - my_network
    depends_on:
      - ms-sql-server

  ms-sql-server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: MSSQLSERVER2022_EVENTS_API
    hostname: MSSQLSERVER2022
    ports:
      - "1433:1433"
    networks:
      - my_network
    volumes:
      - data:/var/opt/mssql
    env_file:
      - ./env/sqlserver.env

networks:
  my_network:
    driver: bridge
volumes:
  data:
    driver: local
